---
- name: Add Microsoft VS Code repository
  yum_repository:
    name: vscode
    description: Microsoft VS Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: Install desktop environment and GUI development tools
  yum:
    name:
      - "@^gnome-desktop-environment"
      - "@Development Tools"
      - meld
      - code
      - tortoisehg
      - sclo-git25-git-all
      - firefox
      - flatpak
    state: latest
    use_backend: yum
  become: yes

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: yes
    
- name: Install the pycharm community flatpak system-wide
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
  become: yes

- name: Set vagrant user for autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: vagrant
    mode: '0644'
  become: yes

- name: Enable autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: 'True'
    mode: '0644'
  become: yes

- name: Set GUI boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  become: yes

- name: Enable and start GDM
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: yes

- name: Increase number of files inotify can look for so that vscode can cope with our megarepo
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
  become: yes

- name: Set meld as default hg diff tool
  ini_file:
    path: "/etc/mercurial/hgrc.d/01-ccdc-default.rc"
    section: ui
    option: merge
    value: meld
  become: yes
