---
- name: Add Microsoft VS Code repository
  yum_repository:
    name: vscode
    description: Microsoft VS Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: Install desktop environment and GUI development tools
  yum:
    name:
      - "@^gnome-desktop-environment"
      - "@Development Tools"
      - kdiff3
      - code
      - tortoisehg
      - sclo-git25-git-all
      - firefox
      - snapd
    state: latest
    use_backend: yum
  become: yes

- name: Start and enable snapd
  systemd:
    name: snapd
    state: started
    enabled: yes
  become: yes

- name: Install GUI development tools from snap
  snap:
    name:
      - pycharm-community
    classic: yes
  become: yes

- name: Set vagrant user for autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: vagrant
    mode: '0644'
  become: yes

- name: Enable autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: 'True'
    mode: '0644'
  become: yes

- name: Set GUI boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  become: yes

- name: Enable and start GDM
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: yes
