---
- name: Add Microsoft VS Code repository
  yum_repository:
    name: vscode
    description: Microsoft VS Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Install desktop environment and GUI development tools
  yum:
    name:
      - "@^gnome-desktop-environment"
      - "@Development Tools"
      - firefox
      - flatpak
      - yum-plugin-versionlock
    state: present
    use_backend: yum
  become: true

# Visual studio code versions 1.53 till 1.59 included would not work on Centos 7
# Version 1.60 and above is ok
- name: Install latest version of visual studio code
  yum:
    name:
      - code
    state: present
    use_backend: yum
  become: true

- name: Install VS Code extensions # noqa: command-instead-of-shell
  shell: code --install-extension {{ extension }}
  loop: "{{ visual_studio_extensions }}"
  loop_control:
    loop_var: extension
  ignore_errors: true # noqa: ignore-errors no-changed-when

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install the pycharm community flatpak system-wide
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
  become: true

- name: Set vagrant user for autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: vagrant
    mode: "0644"
  become: true

- name: Enable autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: "True"
    mode: "0644"
  become: true

- name: Set GUI boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  become: true

- name: Enable and start GDM
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: true

- name: Increase number of files inotify can look for so that vscode can cope with our megarepo
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
  become: true
