---
- name: Ensure visual studio code is not installed via rpm
  yum:
    name:
      - code
    state: absent
    use_backend: yum
  become: true

# Example removing a repository and cleaning up metadata cache
- name: Remove Microsoft VS Code repository (and clean up left-over metadata)
  yum_repository:
    name: vscode
    state: absent
  become: true

- name: Install desktop environment and GUI development tools
  yum:
    name:
      - "@^gnome-desktop-environment"
      - "@Development Tools"
      - sclo-git25-git-all
      - firefox
      - flatpak
      - yum-plugin-versionlock
    state: present
    use_backend: yum
  become: true

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install the pycharm community flatpak system-wide
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
  become: true

- name: Install the visual studio code flatpak system-wide
  flatpak:
    name: com.visualstudio.code
    state: present
  become: true

- name: ensure vscode config directory exists
  file:
    state: directory
    recurse: true
    path: "{{ ansible_env.HOME }}/.var/app/com.visualstudio.code/config/Code/User"
    mode: "700"

- name: Push basic setup to start bash via flatpak-spawn
  copy:
    src: "basic-flatpak-vscode-user-settings.json"
    dest: "{{ ansible_env.HOME }}/.var/app/com.visualstudio.code/config/Code/User/settings.json"
    mode: "0600"
    force: false

- name: Install VS Code extensions # noqa: command-instead-of-shell
  shell: flatpak run --system com.visualstudio.code code --install-extension {{ extension }}
  loop: "{{ visual_studio_extensions }}"
  loop_control:
    loop_var: extension
  ignore_errors: true # noqa: ignore-errors no-changed-when

- name: Set vagrant user for autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLogin
    value: vagrant
    mode: "0644"
  become: true

- name: Enable autologin
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: AutomaticLoginEnable
    value: "True"
    mode: "0644"
  become: true

- name: Set GUI boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  become: true

- name: Enable and start GDM
  systemd:
    name: gdm
    state: started
    enabled: yes
  become: true

- name: Increase number of files inotify can look for so that vscode can cope with our megarepo
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
  become: true
