---
- name: Install Gui tools from Homebrew cask
  homebrew_cask:
    name:
      - visual-studio-code
      - firefox
      - araxis-merge
      - tortoisehg
      - pycharm-ce
    state: present

- name: Install VS Code extensions
  shell: /usr/local/bin/code --install-extension {{ extension }} # noqa: command-instead-of-shell
  loop: "{{ visual_studio_extensions }}"
  loop_control:
    loop_var: extension
  ignore_errors: true # noqa: ignore-errors no-changed-when

- name: Install Gui tools from Homebrew
  homebrew:
    name:
      - mitmproxy
    state: present
