---
- name: Install Gui tools from Homebrew cask
  homebrew_cask:
    name:
      - visual-studio-code
      - firefox
      - araxis-merge
      - meld
      - tortoisehg
      - pycharm-ce
    state: present

- name: Install Gui tools from Homebrew
  homebrew:
    name:
      - mitmproxy
    state: present

- name: Set meld as default hg diff tool
  ini_file:
    path: "/etc/mercurial/hgrc.d/01-ccdc-default.rc"
    section: ui
    option: merge
    value: meld
