---
- name: Add signing key for repo {{ repo.name }}
  become: true
  ansible.builtin.apt_key:
    url: "{{ repo.key }}"
    state: present
  loop: "{{ repositories }}"
  loop_control:
    loop_var: repo

- name: Add repository {{ repo.name }}
  ansible.builtin.apt_repository:
    repo: "{{ repo.repo }}"
    state: present
  become: true
  loop: "{{ repositories }}"
  loop_control:
    loop_var: repo
