---
- name: Install developer productivity gui packages (Centos)
  yum: 
    name:
      - "@X Window System"
      - xeyes # for testing
      - kdiff3
#      - tortoisehg
#      - vscode
#      - qt-creator: latest
#      - firefox: latest
    state: latest
  when: "ansible_os_family == 'RedHat'"

- name: Install developer productivity gui packages (Debian)
  yum: 
    name:
      - kdiff3
#      - tortoisehg
#      - vscode
#      - qt-creator: latest
#      - firefox: latest
    state: latest
  when: "ansible_os_family == 'Debian'"
  
- name: Install developer productivity gui packages (MacOS)
  homebrew:
    name:
      - 'm-cli'
      - clang-format
      - midnight-commander
      - sqldiff
      - sqlite
      - ctags
      - screen
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: developer productivity gui packages (windows)
  win_chocolatey:
    name: 
      - mc
    state: present
  when: "ansible_os_family == 'Windows'"
