- name: Add YUM repositories
  ansible.builtin.yum_repository:
    name: "{{ item.shortname }}"
    description: "{{ item.name }}"
    baseurl: "{{ item.repo }}"
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: "{{ item.key }}"
    enabled: true
    state: present
  loop: "{{ repositories }}"
  become: true
