- name: Add YUM repositories
  ansible.builtin.yum_repository:
    name: "{{ item.shortname }}"
    description: "{{ item.name }}"
    baseurl: "{{ item.repo }}"
    gpgcheck: yes
    gpgkey: "{{ item.key }}"
    enabled: yes
  loop: "{{ repositories }}"
  become: true