---
- name: Install GUI developer tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ system_packages }}"
    state: present

- name: Install VS Code extensions
  ansible.windows.win_shell: code --install-extension {{ extension }}
  loop: "{{ visual_studio_extensions }}"
  loop_control:
    loop_var: extension
  ignore_errors: true  # noqa: ignore-errors
