---
- name: Install GUI developer tools
  win_chocolatey:
    name:
      - araxismerge
      - meld
      - vscode
      - tortoisehg
      - firefox
      - fiddler
      - pycharm-community
    state: present

- name: Set meld as default hg diff tool
  win_lineinfile:
    path: "{{ ansible_facts.env['ProgramData'] }}/Mercurial/hgrc.d/01-ccdc-default.rc"
    regexp: "(^merge\s*=)"
    line: "$1 meld"
