---
- name: Install GUI developer tools
  win_chocolatey:
    name:
      - araxismerge
      - vscode
      - tortoisehg
      - firefox
      - fiddler
      - pycharm-community
    state: present

- name: Install VS Code extensions
  win_shell: code --install-extension {{ extension }}
  loop: "{{ visual_studio_extensions }}"
  loop_control:
    loop_var: extension
  ignore_errors: true # noqa: ignore-errors
